#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceFeatures
runApplication blockMesh
runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite
runApplication reconstructParMesh -constant
runApplication checkMesh -allGeometry
#------------------------------------------------------------------------------
