#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

date

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runParallel patchSummary
runParallel potentialFoam
runParallel $(getApplication)

date
#------------------------------------------------------------------------------
